services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # volumesはホストのルートディレクトリをdockerコンテナの/appにマウントする
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    # env_file:  # 環境変数
    #   - .env
    depends_on:
      - db
    tty: true

  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: FAMILIA_COPILOT
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db-data:
